# What is a Function ? 

collection of statements to slove a specific task. is that correct ? 

# Why Functions are used not Statements ? 

Beause who just want to write same code again and again ? right
so reuseability is the factor we use functions 

# How does a function really works ? 

1. Defination -> know what to do and how to do ?
2. Calling -> Repeat Defination Whenever needed  ? 
3. Return -> Always get somthing whenever we call a function ? 

In [1]:
def hello():
    print("Hello World")
    

In [2]:
r = hello()
print(print(r))

Hello World
None
None


In [3]:
#function can return also
def hello():
    return "Hello World"

In [6]:
#msg = hello()
print(hello())

Hello World


In [11]:
#function can also take information to process
def hello(name): # formal arguments or formal parameters
    print("Hello World !")
    print("Welcome user, ",name)
    return False #exit status
    

In [12]:
if hello(input("Enter your name : ")) : 
         print("Function Sucessfully Exited")
else :
         print("There is an error in function ")

Enter your name : sachin yadav
Hello World !
Welcome user,  sachin yadav
There is an error in function 


In [13]:
def prime(num):
    from math import sqrt
    check = round(sqrt(num)+1)
    for ch in range(2,check):
        if num % ch == 0 :
            return False
    return True

In [16]:
def main():
    num = int(input("Enter a Number : "))
    if prime(num) :
        print("Given no. {} is a Prime Number ".format(num))
    else : 
        print("Given no. {} is not a Prime Number ".format(num))

In [17]:
main()

Enter a Number : 127
Given no. 127 is a Prime Number 


In [18]:
prime(1937811)

False

In [26]:
def prime_range(start,end):
    c = 0
    for var in range(start,end+1):
        if prime(var):
            print(var,end=', ')
            c = c + 1
    print("Total {} Prime Numbers in range({},{})".format(c,start,end))
    print()

In [29]:
s,e = map(int,input("Enter start,end point : ").strip().split(','))
prime_range(s,e)

Enter start,end point : 1100,1200
1103, 1109, 1117, 1123, 1129, 1151, 1153, 1163, 1171, 1181, 1187, 1193, Total 12 Prime Numbers in range(1100,1200)



In [30]:
s = input("Type something")
k = s.split(',')
print(type(k))
print(k)

Type somethingsachin,ram,shyam,hari,mohan,
<class 'list'>
['sachin', 'ram', 'shyam', 'hari', 'mohan', '']


In [31]:
def mymap(func,seq):
    r = []
    for var in seq : 
        k = func(var)
        r.append(k)
    return r

In [32]:
x = input("Float values as , seprated : ").split(',')
print("Before X = ",x)
x = mymap(float,x)
print("After X = ",x)

Float values as , seprated : 123,4567.44,3446,2143.45,234464.465,23446.67
Before X =  ['123', '4567.44', '3446', '2143.45', '234464.465', '23446.67']
After X =  [123.0, 4567.44, 3446.0, 2143.45, 234464.465, 23446.67]


In [33]:
x = input("Float values as , seprated : ").split(',')
print("Before X = ",x)
x = mymap(int,x)
print("After X = ",x)

Float values as , seprated : 1,2,3,4,56,7
Before X =  ['1', '2', '3', '4', '56', '7']
After X =  [1, 2, 3, 4, 56, 7]


In [41]:
def area(r,b=0,c=0):
    if r and b and c :
        from math import sqrt
        s = ( r + b + c ) / 2
        A = sqrt(s*(s-r)*(s-b)*(s-c))
        return A
    elif r and b :
        return r*b
    else : 
        from math import pi 
        return r*r*pi

In [42]:
print(area(3))

28.274333882308138


In [43]:
print(area(3,5))

15


In [44]:
print(area(60,60,60))

1558.8457268119896


In [46]:
prime(num=103424)

False

In [47]:
def fun(a,b=0,c=0) :
    print("A = ",a)
    print("B = ",b)
    print("C = ",c)

In [51]:
fun(c=30,b=-20,a=22) #keywords arguments

A =  22
B =  -20
C =  30


In [52]:
fun(14,b=4)

A =  14
B =  4
C =  0


In [59]:
fun(1,b=3,c=5)

A =  1
B =  3
C =  5


In [60]:
def eve(*args):
    for var in args :
        if var % 2 == 0 : 
            print(var, end=', ')
    

In [64]:
eve(2,3,35,643,4,24,6,3,24,25,3,4,25,52,43,466,5)

2, 4, 24, 6, 24, 4, 52, 466, 

In [73]:
def main():
    eve(*map(int,input("Enter , seprated values : ").split(',')))
    if input("Press a key to continue : ") :
        main()

In [78]:
main()

Enter , seprated values : 1,2
2, Press a key to continue : aksf
Enter , seprated values : 1,2,3,4,5
2, 4, Press a key to continue : 


In [79]:
def mydata(**kwargs):
    for key,value in kwargs.items() :
        print("{}={}".format(key,value))

In [80]:
mydata(name='python',version=3.6,scope='world wide')

name=python
version=3.6
scope=world wide


In [86]:
d  = { 
     '1':'one',
     '2':'two',
     '3':'three',
     '4':'four',
    }

In [87]:
mydata(**d)

1=one
2=two
3=three
4=four


In [6]:
def last_func(pos,key=10,*args,**kwargs):
    """I used to print all arguments.""" #doc-string
    print("Positional Argument is ",pos)
    print("Keyword / Default Argument is ",key)
    print("Here are your multiple Arguments as Tuple")
    c = 1
    for value in args:
        print("Args[{}] : {}".format(c,value))
        c = c + 1
    print("Here are your arguments as Dictionary")
    for key,value in kwargs.items() :
        print("{}={}".format(key,value))
    print("\nThanks for using this function")

In [2]:
print(last_func.__doc__)

I used to print all arguments.


In [3]:
last_func('sachin')

Positional Argument is  sachin
Keyword / Default Argument is  10
Here are your multiple Arguments as Tuple
Here are your arguments as Dictionary

Thanks for using this function


In [4]:
last_func('sachin','python')

Positional Argument is  sachin
Keyword / Default Argument is  python
Here are your multiple Arguments as Tuple
Here are your arguments as Dictionary

Thanks for using this function


In [8]:
l = [ 12,3,4,6,7,54,3,4,56,67 ]
last_func('sachin','python',*l)

Positional Argument is  sachin
Keyword / Default Argument is  python
Here are your multiple Arguments as Tuple
Args[1] : 12
Args[2] : 3
Args[3] : 4
Args[4] : 6
Args[5] : 7
Args[6] : 54
Args[7] : 3
Args[8] : 4
Args[9] : 56
Args[10] : 67
Here are your arguments as Dictionary

Thanks for using this function


In [9]:
last_func('hi','hello','bye','challo','good',name='sachin',subject='python',batch='evening batch')

Positional Argument is  hi
Keyword / Default Argument is  hello
Here are your multiple Arguments as Tuple
Args[1] : bye
Args[2] : challo
Args[3] : good
Here are your arguments as Dictionary
name=sachin
subject=python
batch=evening batch

Thanks for using this function


In [10]:
del last_func

In [11]:
last_func

NameError: name 'last_func' is not defined

In [12]:
x = 5

In [13]:
x

5

In [14]:
x = x + 5

In [15]:
x

10

In [19]:
def fun():
    y = 5
    print(y)

In [21]:
fun()


5


In [22]:
y

NameError: name 'y' is not defined

In [23]:
def fun():
    x = x + 5
    print(x)

In [24]:
x

10

In [25]:
fun()

UnboundLocalError: local variable 'x' referenced before assignment

In [26]:
x

10

In [27]:
def fun():
    x = 5
    x = x ** 2
    print(x)
print(x)
fun()
print(x)

10
25
10


In [29]:
x = 5
x

5

In [30]:
def fun():
    global x
    x = x ** 2
    print(x)
print(x)
fun()
print(x)

5
25
25


In [31]:
msg = "Hi I am global messsage"

In [32]:
msg

'Hi I am global messsage'

In [33]:
def fun1():
    print("Global Message : ",msg)
    

In [35]:
def fun2():
    global msg
    print("Previous msg : ",msg)
    msg = input("New msg : ")

In [36]:
fun1()

Global Message :  Hi I am global messsage


In [37]:
fun2()

Previous msg :  Hi I am global messsage
New msg : hi i am your boss i will update you regurarly


In [38]:
fun1()

Global Message :  hi i am your boss i will update you regurarly


In [39]:
def hello():
    print("Hello World")
    if input("Press a key to continue") :
        hello()

In [40]:
hello()

Hello World
Press a key to continuek
Hello World
Press a key to continuek
Hello World
Press a key to continuek
Hello World
Press a key to continuek
Hello World
Press a key to continuej
Hello World
Press a key to continuej
Hello World
Press a key to continuejj
Hello World
Press a key to continue


In [41]:
def fact(num):
    if num == 1 :
        return 1
    return num*fact(num-1)

In [42]:
fact(5)

120

In [44]:
from math import sqrt
def prime(num,c=2):
    if c <= round(sqrt(num)) :
        if num % c == 0 :
            return False
    else :
        return True
    return prime(num,c+1)

In [45]:
prime(121)

False

In [47]:
def nprime(num,c=2):
    if  num % c == 0 :
        return False
    if c <= round(sqrt(num)) :
        return nprime(num,c+1)
    return True

In [49]:
nprime(127)

True

In [54]:
p = lambda x,p: x**p

In [55]:
p(5,3)

125

In [56]:
p(7,3)

343

In [59]:
even_odd = lambda x : False if x % 2 else True

In [60]:
even_odd(3)

False

In [61]:
even_odd(146)

True

In [62]:
fact = lambda x: 1 if x == 1 else x*fact(x-1)

In [63]:
fact(5)

120

In [64]:
fact(12)

479001600

In [65]:
def fx(x,y):
    return x*y

In [66]:
x = [ 5.5,4.5,5.10,6,6.2,4.8,5.2,]
f = [ 10,15,20,3,5,25,30 ]


In [69]:
r = map(lambda x,y:x*y,x,f)

In [70]:
s_fx = sum(r)
s_f = sum(f)
mean = s_fx / s_f
print(mean)

5.087962962962963


In [71]:
import numpy as np


In [72]:
x = np.random.randint(45,85,50)

In [73]:
x

array([62, 82, 64, 54, 50, 68, 51, 72, 62, 75, 69, 84, 46, 82, 73, 59, 82,
       58, 79, 50, 82, 56, 65, 45, 73, 66, 61, 49, 47, 62, 56, 53, 61, 79,
       67, 71, 56, 49, 49, 60, 75, 55, 49, 54, 75, 70, 67, 80, 55, 84])

In [76]:
r = list(map(lambda x:True if x % 2 == 0 else False,x))

In [77]:
x

array([62, 82, 64, 54, 50, 68, 51, 72, 62, 75, 69, 84, 46, 82, 73, 59, 82,
       58, 79, 50, 82, 56, 65, 45, 73, 66, 61, 49, 47, 62, 56, 53, 61, 79,
       67, 71, 56, 49, 49, 60, 75, 55, 49, 54, 75, 70, 67, 80, 55, 84])

In [79]:
print(r)

[True, True, True, True, True, True, False, True, True, False, False, True, True, True, False, False, True, True, False, True, True, True, False, False, False, True, False, False, False, True, True, False, False, False, False, False, True, False, False, True, False, False, False, True, False, True, False, True, False, True]


In [80]:
r = list(filter(lambda x:True if x % 2 == 0 else False,x))

In [82]:
x

array([62, 82, 64, 54, 50, 68, 51, 72, 62, 75, 69, 84, 46, 82, 73, 59, 82,
       58, 79, 50, 82, 56, 65, 45, 73, 66, 61, 49, 47, 62, 56, 53, 61, 79,
       67, 71, 56, 49, 49, 60, 75, 55, 49, 54, 75, 70, 67, 80, 55, 84])

In [83]:
print(r)

[62, 82, 64, 54, 50, 68, 72, 62, 84, 46, 82, 82, 58, 50, 82, 56, 66, 62, 56, 56, 60, 54, 70, 80, 84]


In [95]:
r = list(filter(prime,x))

In [89]:
x

array([62, 82, 64, 54, 50, 68, 51, 72, 62, 75, 69, 84, 46, 82, 73, 59, 82,
       58, 79, 50, 82, 56, 65, 45, 73, 66, 61, 49, 47, 62, 56, 53, 61, 79,
       67, 71, 56, 49, 49, 60, 75, 55, 49, 54, 75, 70, 67, 80, 55, 84])

In [90]:
print(r)

[73, 59, 79, 73, 61, 47, 53, 61, 79, 67, 71, 67]


In [91]:
from functools import reduce

In [92]:
r = reduce(lambda x,y: x + y ,filter(prime,x))

In [93]:
r

790

In [94]:
sum(x)

3193

In [96]:
sum(r)

790

In [1]:
def fun(*args):
    print(args)

In [2]:
fun()
print()
fun(1)
print()
fun(1,2,3,4,'helllo',46,56434,3,24)

()

(1,)

(1, 2, 3, 4, 'helllo', 46, 56434, 3, 24)


In [3]:
def fun(**kwargs):
    print(kwargs)
    print()

In [6]:
fun(x=5,name='python')

{'x': 5, 'name': 'python'}



In [7]:
fun(name='python',version=3.6,framwork=['Django','Flask','Web2py'])

{'name': 'python', 'version': 3.6, 'framwork': ['Django', 'Flask', 'Web2py']}



In [9]:
def fun(x,y=5,*args,**kwargs):
    print("Positional : ",x)
    print("Keyword / Default : ",y)
    print("Tuple Arguments : ",args)
    print("Dictionary Arguments : ",kwargs)

In [10]:
fun('hello')

Positional :  hello
Keyword / Default :  5
Tuple Arguments :  ()
Dictionary Arguments :  {}


In [12]:
fun('hello','bye',1,2,3,45,6,name='something',hello='hey bhagwaan')

Positional :  hello
Keyword / Default :  bye
Tuple Arguments :  (1, 2, 3, 45, 6)
Dictionary Arguments :  {'name': 'something', 'hello': 'hey bhagwaan'}


In [13]:
k = [ '1','2','3','4','5']

In [14]:
r = []
for value in k :
    x = int(value)
    r.append(x)

In [15]:
r

[1, 2, 3, 4, 5]

In [16]:
k

['1', '2', '3', '4', '5']

In [17]:
r = list(map(int,k))
r

[1, 2, 3, 4, 5]

In [18]:
x = input()

1 2 3 4 5


In [20]:
x

'1 2 3 4 5'

In [21]:
y = x.split()

In [22]:
y

['1', '2', '3', '4', '5']

In [23]:
z = list(map(int,y))

In [24]:
z

[1, 2, 3, 4, 5]

In [25]:
x = list(map(int,input().split(',')))
x

   1,2 ,3,4,5,6, 7


[1, 2, 3, 4, 5, 6, 7]

In [28]:
x = [ 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]
x.__sizeof__()

248

In [29]:
y = range(1,27)
y.__sizeof__()

48

In [31]:
print(x)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]


In [34]:
y = iter(y)

In [39]:
eve_odd = lambda num : True if num % 2 == 0 else False

In [41]:
eve_odd(12)

True

In [42]:
k = list(map(eve_odd,x))

In [45]:
print(k)
print(x)

[False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]


In [47]:
r = list(filter(eve_odd,x))
print(r)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26]


In [48]:
from functools import reduce

In [50]:
p = reduce(lambda m,n:m+n,x)
p

351

# Closures in Python

In [60]:
def hello(x):
    def hi():
        nonlocal x
        x = 'Hello , '+x
        print(x)
    return hi

In [61]:
k = hello('sachin')

In [62]:
k()

Hello , sachin


In [101]:
def hello(myfun):
    def hi(*name):
        print("*"*50)
        myfun(*name)
        print("*"*50)
    return hi

In [102]:
def hey(var):
    print(var.center(len(var*3)))

In [103]:
n_hi = hello(hey)
n_hi('sachin yadav')

**************************************************
            sachin yadav            
**************************************************


In [104]:
def decorate(oldfunc):
    def worker(*name):
        k = 50
        print("-"*k)
        print()
        oldfunc(*name)
        print()
        print("-"*k)
    return worker

In [105]:
n = n=decorate(n_hi)

In [106]:
n('Hello World How are ')

--------------------------------------------------

**************************************************
                    Hello World How are                     
**************************************************

--------------------------------------------------


In [107]:
@decorate
@hello
def add(x,y):
    print()
    print("X = ",x)
    print("Y = ",y)
    print("{} + {} = {}".format(x,y,x+y))
    print()

In [100]:
add(6,8)

--------------------------------------------------

**************************************************

X =  6
Y =  8
6 + 8 = 14

**************************************************

--------------------------------------------------


In [112]:
def prime(num):
    from math import sqrt
    check = round(sqrt(num)+1)
    for ch in range(2,check):
        if num % ch == 0 :
            return False
    return True

In [113]:
def prime_decorator(prime):
    def new_prime(num):
        print("*"*50)
        print("*"*50)
        print()
        if prime(num) :
            print("{} is Prime".format(num).center(50))
        else :
            print("{} is Not Prime".format(num).center(50))
        print()
        print("*"*50)
        print("*"*50)
    return new_prime

In [114]:
new_prime = prime_decorator(prime)
new_prime(int(input("Enter a number : ")))

Enter a number : 12341
**************************************************
**************************************************

                12341 is Not Prime                

**************************************************
**************************************************


In [115]:
@prime_decorator
def old_Prime(num):
    from math import sqrt
    check = round(sqrt(num)+1)
    for ch in range(2,check):
        if num % ch == 0 :
            return False
    return True

In [116]:
old_Prime(123321)

**************************************************
**************************************************

               123321 is Not Prime                

**************************************************
**************************************************
